package interview.pilot.async.domain;

public enum AsyncTaskType {
  RESUME_ANALYSIS,
  HIRING_WORK,
  INTERVIEW_QUESTION_PREPARATION,
  INTERVIEW_EVALUATION,
  ANSWER_EVALUATION,
  KNOWLEDGE_DOCUMENT_INDEX,
  KNOWLEDGE_DOCUMENT_DELETE,
  VOICE_TRANSCRIPTION,
  QUESTION_SPEECH_SYNTHESIS
}
