package interview.pilot.async.domain;

public enum AsyncTaskType {
  RESUME_ANALYSIS,
  INTERVIEW_QUESTION_PREPARATION,
  INTERVIEW_EVALUATION,
  KNOWLEDGE_DOCUMENT_INDEX,
  KNOWLEDGE_DOCUMENT_DELETE,
  VOICE_TRANSCRIPTION
}
